name: 'rocrate-to-html'
description: 'This creates a preview html file from the rocrate json metadata file and publishes them on github pages'
inputs:
  crate_path:
    description: 'Path to ro-crate-metadata.json'
    required: false
    default: '.'
outputs:
  preview:
    description: 'HTML preview of the RO Crate'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.crate_path }}
