name: 'rocrate-to-pages'
description: 'This takes the rocrate json and preview.html files and publishes them on github pages'
branding:
  icon: 'upload-cloud'
  color: 'red'
inputs:
  crate_path:  
    description: 'Path to rocrate files'
    required: false
    default: '.'
  loglevel:
    description: 'Logging verbosity level. Choose from DEBUG, INFO, WARNING, ERROR or CRITICAL'
    required: false
    default: 'INFO' 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.crate_path }}
    - ${{ inputs.loglevel }}