on:
  push:
    tags:
      - 'v+[0-9]+.0+.0+'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
          tag_prefix: v
          use_github_release_notes: true
          
