on:
  push:
    branches:
      - main

jobs:

  release-on-push:
  
    runs-on: ubuntu-latest
    steps:
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} !=~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
        fi
    - name: Build
      if: steps.check-tag.outputs.match == 'true'
      run: |
        echo "Tag is a match"

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          steps:
            - uses: rymndhng/release-on-push-action@master
              with:
                bump_version_scheme: major
                tag_prefix: v
                use_github_release_notes: true
          
