#on push look if the current tag is v*.0.0
on:
  push:
    branches:
      - main

#check if the current tag is v*.0.0
name: Release Management

jobs:
  release_management:
    name: Check if ready for release
    runs-on: ubuntu-latest
    steps:
      name: find name of the current repo 
    - run: echo ${{ github.event.repository.name }}
