name: On_Push_Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Environment
      uses: actions/setup-node@v3
      with:
        node-version: 18.1.0
    - run: npm install
    # - run: npm run build

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile
  
  create-latest-tag:
      runs-on: ubuntu-latest
      steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag or branch with this input.
          # Default: 'latest'
          ref: latest

          # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
          # Default: ''
          description: Latest version of the rocrate-to-html 

          # Force-update a branch instead of using a tag.
          # Default: false
          force-branch: false
          
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
