name: On_Push_Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Environment
      uses: actions/setup-node@v3
      with:
        node-version: 18.1.0
    - run: npm install
    # - run: npm run build

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
          
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
          token: ${{ secrets.GITHUB_TOKEN }}
